bumps
1c-syntax/mdclasses pull request #161
Opened 2021-01-01 14:44 UTC by theshadowco

- переезд на gradle 6.7.1. и обновление либ
 - обновление копирайтов (NewYear)

2021-01-01 14:47 UTC, nixel2007 requested changes
Проверка implementation

2021-01-01 14:48 UTC, nixel2007 commented
Так... Или я напутал, и api появляется только в java-library?..

2021-01-01 16:51 UTC, otymko commented
@nixel2007 api() вроде только в java-library

2021-01-01 18:13 UTC, nixel2007 approved these changes

2021-01-02 04:37 UTC, theshadowco commented
Что ж вы так не доверяете, я ж проверил и `gradlew help --warning-mode=all`,  и тесты ,и сборку....

2021-01-02 08:43 UTC, nixel2007 commented
Текущий проект будет собираться без проблем, проблемы могут возникнуть в проектах, где mdclasses - зависимость :)

вспомни игры с корой.

2021-01-11 04:23 UTC, otymko approved these changes

2021-01-11 05:11 UTC, merged