Feature/add configuration roles
1c-syntax/mdclasses pull request #188
Opened 2021-05-15 06:31 UTC by EvgSychev

идеевские файлы случайно зацепил

2021-05-15 09:21 UTC, otymko requested changes

2021-05-15 09:21 UTC, otymko commented on .idea/compiler.xml
> +</project>
@EvgSychev Нужно откатить эти изменения

2021-05-15 09:21 UTC, otymko commented on .idea/workspace.xml
> +  <component name="AutoImportSettings">
@EvgSychev Нужно откатить эти изменения

2021-05-15 09:22 UTC, otymko commented
@EvgSychev в остальном все в порядке. Универсальный getter для различных объектов метаданных напишем отдельно.

2021-05-16 16:17 UTC, EvgSychev commented
Как сделать откат двух файлов? Гуглинг ничего не говорит как откатить то что уже запулреквестено. Реверт я так понимаю не поможет, так как я пытался руками откатить compiler.xml.

2021-05-17 03:30 UTC, otymko commented
@EvgSychev
Способ 1: перенести изменения в новую ветку и отправить их через PR
Способ 2: из ветки develop достать эта два файла, закинуть в нашу ветку, написать что это revert
Способ 3: force push. Откатываете изменения до первого коммита в ветке, заново фиксируете свои изменений. Отправляете в свою ветку push в режиме force.

2021-05-18 16:51 UTC, closed without merging